name: pawesomeid_mobile
description: Decentralized Identity Solution for Pets
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  # google_mlkit_face_detection: ^0.8.0
  web3dart: ^2.7.1
  provider: ^6.1.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  walletconnect_dart: ^0.0.11
  shared_preferences: ^2.2.2
  qr_flutter: ^4.0.0
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  intl: ^0.17.0
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.7
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/